### PR TITLE
allow notifications on gcm fixes #70

### LINKED ISSUE #70: Send notifications with gcm
See https://github.com/alexjlockwood/gcm/issues/9
I will do a PR to both the gcm module and Incus to allow this option

### PR DESCRIPTION
**Pull request by AdriVanHoudt**
fixes #70 

This can only be merged after https://github.com/alexjlockwood/gcm/pull/10
I will keep this up to date if the gcm PR changes

As stated in the other PR, not familiar with Go so if this needs any changed let me know.

### CODE REVIEW

**Comment by AdriVanHoudt** [comment]
I am assuming it error because atm gcm only takes 2 arguments

**Comment by AdriVanHoudt** [comment]
Would this be accepted with the change on the gcm library?

**Comment by jacob-pascual** [comment]
It looks like you have a syntax error. 

A best approach would be to let us fork your gcm library and depend on that until gcm merges your branch.

I will get to this this week. Thanks!

**Comment by AdriVanHoudt** [comment]
Yeah I am used to Javascript where function params are optional so I implemented it that way so it might not break but that turned out to not be the case :D the author of the lib did let know to work on it but no progress yet. If you would like some changes to the interface or something now is the time ;)

**Comment by AdriVanHoudt** [comment]
So what is the progress on this? There was 1 more request on the PR to allow a ios specific key but I will add it the moment I know you will be using the fork I made.

**Pull request closed without merging**
